In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pathfinding.core.grid import Grid
from pathfinding.finder.bi_a_star import BiAStarFinder
from pathfinding.finder.dijkstra import DijkstraFinder
from pathfinding.core.diagonal_movement import DiagonalMovement

In [30]:
start = (11, 19)
end = (17, 12)
walkable ="""[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0]
[0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0]
[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0]
[0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0]
[0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0]
[0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0]
[0 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
[0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0]
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 9 0 0]
[0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0]
[0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0]
[0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0]
[0 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0]
[0 1 1 0 0 0 0 0 0 1 1 1 6 1 1 1 1 1 1 0 1 0]
[0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0]
[0 1 1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 0]
[0 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 1 1 1 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]"""

world = """[[2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2]
[2  3  3  2  2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  2]
[2  3  3  2  2  2  2  1  1  1  1  1  1  1  2  2  1  1  1  1  1  2]
[2  3  3  3  3  3  2  2  1  1  1  1  1  1  1  2  1  1  1  1  1  2]
[2  2  2  3  3  3  3  3  3  3  1  3  3  3  3  3  3  3  3  1  3  2]
[2  2  2  3  3  3  1  1  1  1  1  1  1  3  1  1  1  1  1  1  3  2]
[2  2  3  3  3  3  3  1  1  1  1  1  1  3  1  1  1  1  1  1  3  2]
[2  2  3  3  3  3  3  1  1  1  1  1  1  3  1  1  1  1  1  1  3  2]
[2  2  3  3  3  3  3  1  1  1  1  1  1  3  1  1  1  1  1  1  3  2]
[2  2  2  3  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  3  2]
[2  2  2  3  1  1  3  3  3  1  3  3  3  1  3  3  3  3  1  1  1  2]
[2  2  2  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  2]
[2  2  2  3  1  1  1  1  1  1  3  3  3  3  3  3  1  3  3  3  3  2]
[2  2  2  3  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  2]
[2  2  2  3  1  1  1  1  1  1  1  1  3  3  1  3  3  3  3  3  2  2]
[2  1  1  1  1  1  1  1  1  1  1  1  3  3  3  3  2  1  1  1  1  2]
[2  1  1  3  1  1  1  1  3  3 12  3  3  3  3  3  1  2  1  1  1  2]
[2  1  1  3  3  3  3  3  3  1  1  1  5  1  1  1  1  1  1  3  1  2]
[2  1  1  3  1  3  1  1 12  1  1  1  1  1  1  3  1  2  1  1  1  2]
[2  1  1  3  1  3  1  1  3  3  1  3  3  3  3  3  2  1  1  1  2  2]
[2  1  1  1  1  1  1  2  1  1  1  1  1  2  2  2  1  1  1  1  2  2]
[2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2]]"""

In [31]:
walkable = walkable.replace(" ", ",").replace("\n", ",")
walkable_np = np.array(eval(walkable))
walkable_np[start] = 1
walkable_np[end] = 1
walkable_np[start[0]+3, start[1]] = 3

In [32]:
world = ",".join(world.split())
world_np = np.array(eval(world))

In [33]:
grid = Grid(matrix=walkable_np)
start = grid.node(start[1], start[0])
end = grid.node(end[1], end[0])
finder = BiAStarFinder(diagonal_movement=DiagonalMovement.never)
path, _ = finder.find_path(start, end, grid)

In [34]:
path

[GridNode(x=19, y=11, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=18, y=11, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=17, y=11, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=16, y=11, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=16, y=12, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=16, y=13, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=17, y=13, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=18, y=13, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=19, y=13, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=19, y=14, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=19, y=15, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=18, y=15, walkable=True, weight=1, grid_id=None, connections=None),
 GridNode(x=18, y=16, walkable=True, wei